### ISSUE TITLE
Preferential Voting

### ISSUE THREAD

**Issue by cassar** [cassar/open-civic-platform#21]
## Background

Positions should be ordered by preference.

## Tasks

- [ ] Implement a preference_number field on supports.
- [ ] Allow a person to support multiple positions on an issue.
- [ ] Rework controller actions around "shifting support" to rearrange preferences.
